apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.25.4
          volumeMounts:
            - name: myapp-volume
              mountPath: /data
          ports:
            - containerPort: 80
          env:
            - name: NGINX_PORT
              value: "8080"
            - name: NGINX_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: myapp-config
                  key: foo
          resources:
            limits:
              memory: "256Mi"  # Maximum memory allowed
              cpu: "200m"      # Maximum CPU allowed (200 milliCPU)
            requests:
              memory: "128Mi"  # Initial memory request
              cpu: "100m"      # Initial CPU request
      volumes:
        - name: myapp-volume
          persistentVolumeClaim:
            claimName: myapp-pvc
