apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
    tier: front-end
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
