- name: Install MySQL Server
  hosts: mysql_server
  become: true
  tasks:
    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

  handlers:
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted