- name: Install PHP and PHP-FPM
  hosts: php_fpm_servers
  become: true
  tasks:
    - name: Install PHP and PHP-FPM
      apt:
        name: 
          - nginx
          - php{{ php_version }}
          - php{{ php_version }}-fpm
        state: present

  vars:
    php_version: "8.2"

  handlers:
    - name: Restart PHP-FPM
      service:
        name: php{{ php_version }}-fpm
        state: restarted