services:
  pub:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "start"]
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - app-node-modules:/app/node_modules

  sub:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "client"]
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - app-node-modules:/app/node_modules

  redis:
    image: "redis/redis-stack"
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"

  redis-commander:
    image: "rediscommander/redis-commander:latest"
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis    

  redis-insight:
    image: "redislabs/redisinsight:latest"
    ports:
      - "5540:5540"
    environment:
      - REDIS_URI=redis://redis:6379
    depends_on:
      - redis

volumes:
  redis:
  app-node-modules: